site_name: whakamarie

# Documentation and theme
docs_dir: 'docs'
theme:
  name: 'material'
  # Color
  palette:
      scheme: slate
      primary: blue gray
      accent: gray
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
