site_name: whakamarie

# Documentation and theme
docs_dir: 'docs'
theme:
  name: 'material'
  # 配色設定
  - scheme: default
    toggle:
        icon: material/toggle-switch-off-outline
        name: ダークモード
  - scheme: slate
    toggle:
        icon: material/toggle-switch
        name: ライトモード
