site_name: whakamarie

# Documentation and theme
docs_dir: 'docs'
theme:
  name: 'material'
  language: ja
  # Color
  palette:
      scheme: slate
      primary: teal
      accent: gray
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-W7KQBBZSKT
  search:
    language: 'jp'

plugins:
  - tags
